-- Generated by Oracle SQL Developer Data Modeler 18.1.0.082.1041
--   at:        2025-10-04 23:27:37 PKT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE books (
    book_id   NUMBER NOT NULL,
    name      VARCHAR2(20) NOT NULL
);

ALTER TABLE books ADD CONSTRAINT books_pk PRIMARY KEY ( book_id );

CREATE TABLE buyer (
    buyer_id        NUMBER NOT NULL,
    name            VARCHAR2(20) NOT NULL,
    books_book_id   NUMBER NOT NULL
);

ALTER TABLE buyer ADD CONSTRAINT buyer_pk PRIMARY KEY ( buyer_id,
                                                        books_book_id );

ALTER TABLE buyer
    ADD CONSTRAINT buyer_books_fk FOREIGN KEY ( books_book_id )
        REFERENCES books ( book_id );
        
alter table buyer add age int;
alter table buyer add constraint age_const check(age > 18);
        
insert into books values(1,'A');
insert into books values(2,'B');
insert into books values(3,'C');
insert into books values(4,'D');
insert into books values(5,'E');

insert into buyer values(1,'Raghib',1);
insert into buyer values(2,'Adina',1);
insert into buyer values(3,'Fahad',2);

update BUYER set age = 20 where buyer_id IN(1,2,3);

select * from books;
select * from buyer;

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             2
-- CREATE INDEX                             0
-- ALTER TABLE                              3
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
